<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.2.335">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>bartolome_flores_vciaria-practicafinal</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<script src="Bartolome_Flores_Vciaria-PracticaFinal_files/libs/clipboard/clipboard.min.js"></script>
<script src="Bartolome_Flores_Vciaria-PracticaFinal_files/libs/quarto-html/quarto.js"></script>
<script src="Bartolome_Flores_Vciaria-PracticaFinal_files/libs/quarto-html/popper.min.js"></script>
<script src="Bartolome_Flores_Vciaria-PracticaFinal_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="Bartolome_Flores_Vciaria-PracticaFinal_files/libs/quarto-html/anchor.min.js"></script>
<link href="Bartolome_Flores_Vciaria-PracticaFinal_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="Bartolome_Flores_Vciaria-PracticaFinal_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="Bartolome_Flores_Vciaria-PracticaFinal_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="Bartolome_Flores_Vciaria-PracticaFinal_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="Bartolome_Flores_Vciaria-PracticaFinal_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">

  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">



<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Importación librerías</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">"dslabs"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><strong>Cargar los datos en un dataframe llamado: airbnb</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>airbnb<span class="ot">&lt;-</span><span class="fu">read.csv</span>(<span class="st">'data//airbnb.csv'</span>,<span class="at">sep =</span> <span class="st">','</span>, <span class="at">stringsAsFactors =</span> T)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><strong>Mostrar las primeras 6 filas del dataframe</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(airbnb,<span class="at">n=</span><span class="dv">6</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  Zipcode Neighbourhood.Cleansed Property.Type       Room.Type Accommodates
1   28004            Universidad     Apartment    Private room            2
2   28004            Universidad     Apartment Entire home/apt            6
3   28004            Universidad     Apartment Entire home/apt            3
4   28004            Universidad          Loft Entire home/apt            3
5   28015            Universidad     Apartment Entire home/apt            5
6   28004            Universidad     Apartment Entire home/apt            2
  Bathrooms Bedrooms Beds Bed.Type
1         2        1    1 Real Bed
2         1        3    5 Real Bed
3         1        2    2 Real Bed
4         2        1    1 Real Bed
5         1        1    1 Real Bed
6         1        0    1 Real Bed
                                                                                                                                                                                                                                                                                                                                                         Amenities
1                                                                                                                                                                              TV,Wireless Internet,Kitchen,Pets allowed,Pets live on this property,Buzzer/wireless intercom,Heating,Suitable for events,Washer,First aid kit,Essentials,Lock on bedroom door,Iron
2                                                                                                                                                                                      TV,Internet,Wireless Internet,Air conditioning,Kitchen,Indoor fireplace,Heating,Family/kid friendly,Washer,Dryer,Smoke detector,Carbon monoxide detector,Essentials,Shampoo
3                                                                                                                                                                                           TV,Internet,Wireless Internet,Air conditioning,Kitchen,Doorman,Heating,Family/kid friendly,Washer,Essentials,Shampoo,Hangers,Hair dryer,Iron,Laptop friendly workspace
4                                           TV,Internet,Wireless Internet,Air conditioning,Kitchen,Pets allowed,Breakfast,Elevator in building,Indoor fireplace,Buzzer/wireless intercom,Heating,Washer,Essentials,Shampoo,Hangers,Hair dryer,Iron,Laptop friendly workspace,translation missing: en.hosting_amenity_49,translation missing: en.hosting_amenity_50
5                                                                                                                                                                                                               TV,Wireless Internet,Air conditioning,Kitchen,Smoking allowed,Pets allowed,Elevator in building,Heating,Family/kid friendly,Washer,Essentials,Iron
6 TV,Cable TV,Internet,Wireless Internet,Air conditioning,Wheelchair accessible,Kitchen,Doorman,Elevator in building,Buzzer/wireless intercom,Heating,Washer,Smoke detector,Carbon monoxide detector,First aid kit,Safety card,Fire extinguisher,Essentials,Shampoo,24-hour check-in,Hangers,Hair dryer,Iron,Laptop friendly workspace,Self Check-In,Doorman Entry
  Square.Feet Price Review.Scores.Rating
1          NA    35                   NA
2          NA    92                   96
3          NA    55                   91
4          NA    60                  100
5         538    75                   90
6          NA    55                   95</code></pre>
</div>
</div>
<p><strong>Renombrar las columnas de la siguiente forma:</strong></p>
<table class="table">
<thead>
<tr class="header">
<th>Nombre original</th>
<th>Nuevo nombre</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Zipcode</td>
<td>CodigoPostal</td>
</tr>
<tr class="even">
<td>Neighbourhood.Cleansed</td>
<td>Barrio</td>
</tr>
<tr class="odd">
<td>Property.Type</td>
<td>TipoPropiedad</td>
</tr>
<tr class="even">
<td>Room.Type</td>
<td>TipoAlquiler</td>
</tr>
<tr class="odd">
<td>Accommodates</td>
<td>MaxOcupantes</td>
</tr>
<tr class="even">
<td>Bathrooms</td>
<td>NumBanyos</td>
</tr>
<tr class="odd">
<td>Bedrooms</td>
<td>NumDormitorios</td>
</tr>
<tr class="even">
<td>Beds</td>
<td>NumCamas</td>
</tr>
<tr class="odd">
<td>Bed.Type</td>
<td>TipoCama</td>
</tr>
<tr class="even">
<td>Amenities</td>
<td>Comodidades</td>
</tr>
<tr class="odd">
<td>Square.Feet</td>
<td>PiesCuadrados</td>
</tr>
<tr class="even">
<td>Price</td>
<td>Precio</td>
</tr>
<tr class="odd">
<td>Review.Scores.Rating</td>
<td>Puntuacion</td>
</tr>
</tbody>
</table>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">cat</span>(<span class="st">"Los nombre originales de las columnas son: "</span>, <span class="fu">paste0</span>(<span class="fu">colnames</span>(airbnb), <span class="at">collapse =</span> <span class="st">","</span>)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Los nombre originales de las columnas son:  Zipcode,Neighbourhood.Cleansed,Property.Type,Room.Type,Accommodates,Bathrooms,Bedrooms,Beds,Bed.Type,Amenities,Square.Feet,Price,Review.Scores.RatingNULL</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Renombramos las columnas</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(airbnb) <span class="ot">&lt;-</span><span class="fu">c</span>(<span class="st">"CodigoPostal"</span>,<span class="st">"Barrio"</span>,<span class="st">"TipoPropiedad"</span>,<span class="st">"TipoAlquiler"</span>,<span class="st">"MaxOcupantes"</span>,<span class="st">"NumBanyos"</span>,</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a><span class="st">"NumDormitorios"</span>,<span class="st">"NumCamas"</span>,<span class="st">"TipoCama"</span>,<span class="st">"Comodidades"</span>,<span class="st">"PiesCuadrados"</span>,<span class="st">"Precio"</span>,<span class="st">"Puntuacion"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Los nombres modificados de las columnas son: "</span>, <span class="fu">paste0</span>(<span class="fu">colnames</span>(airbnb), <span class="at">collapse =</span> <span class="st">","</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Los nombres modificados de las columnas son:  CodigoPostal,Barrio,TipoPropiedad,TipoAlquiler,MaxOcupantes,NumBanyos,NumDormitorios,NumCamas,TipoCama,Comodidades,PiesCuadrados,Precio,Puntuacion</code></pre>
</div>
</div>
<p><strong>Crea una nueva columna llamada MetrosCuadrados a partir de la columna PiesCuadrados.</strong></p>
<p>Ayuda: 1 pie cuadrado son 0,092903 metros cuadrdados</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Creamos la columna "MetrosCuadrados" a partir de "PiesCuadrados"</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>airbnb<span class="sc">$</span>MetrosCuadrados <span class="ot">&lt;-</span> airbnb<span class="sc">$</span>PiesCuadrados <span class="sc">*</span> <span class="fl">0.092903</span> </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Miremos el código postal. Es una variable con entradas erróneas. Hay valores como ’‘,’-’ y ‘28’ que deberían ser considerados como NA. Así mismo también debería ser NA todos los que no compiencen por 28, ya que estamos con códigos postales de Madrid</p>
<p>El código postal 28002, 28004 y 28051 tienen entradas repetidas. Por ejemplo las entradas 28002 deberían ir dnetro de 28002</p>
<p>El codigo 2804 debería ser 28004, 2805 deberia ser 28005 y 2815 juncto con 2815 debería ser 28015</p>
<p><strong>Limpia los datos de la columna Codigo Postal</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Antes de la limpieza</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"El listado de CodigoPostal antes de limpieza es: </span><span class="sc">\n\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>El listado de CodigoPostal antes de limpieza es: </code></pre>
</div>
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>airbnb<span class="sc">$</span>CodigoPostal <span class="sc">|&gt;</span> <span class="fu">table</span>(<span class="at">useNA=</span><span class="st">'always'</span>) <span class="sc">|&gt;</span>  <span class="fu">sort</span>(<span class="at">decreasing =</span> <span class="cn">TRUE</span>)<span class="sc">|&gt;</span> <span class="fu">data.frame</span>() <span class="sc">|&gt;</span> <span class="fu">print.data.frame</span>(<span class="at">row.names =</span> <span class="cn">FALSE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>         Var1 Freq
        28012 2060
        28004 1794
        28005 1194
        28013 1019
        28014  630
        28015  600
        28045  495
               439
        28010  384
        28008  338
        28028  263
        28011  250
        28001  231
        28006  218
        28009  216
        28007  206
        28019  200
        28020  192
        28003  185
        28002  170
        28039  160
        28025  123
        28027  122
        28029  110
        28017  107
        28043  103
        28026   93
        28042   90
        28033   89
        28053   85
        28038   77
        28016   76
        28030   73
        28036   67
        28047   67
        28037   65
        28041   63
        28035   59
        28021   58
        28050   58
        28034   45
        28024   44
        28018   43
        28032   33
        28046   32
        28022   30
        28031   27
        28023   23
        28044   19
        28040   16
        28051   16
        28054   12
        28055   12
        28049    3
            -    1
        20013    1
        20126    1
         2015    1
        25008    1
        27004    1
        27013    1
           28    1
       280013    1
 28002\n28002    1
         2804    1
        28048    1
         2805    1
 28051\n28051    1
        28052    1
        28056    1
        28058    1
        28060    1
        28094    1
        28105    1
         2815    1
        28850    1
 Madrid 28004    1
         &lt;NA&gt;    0</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Limpieza de datos por la columna "Codigo Postal"</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>airbnb[<span class="fu">which</span>(airbnb<span class="sc">$</span>CodigoPostal<span class="sc">==</span><span class="st">"Madrid 28004"</span>),<span class="st">'CodigoPostal'</span>] <span class="ot">&lt;-</span> <span class="st">"28004"</span></span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>airbnb[<span class="fu">which</span>(airbnb<span class="sc">$</span>CodigoPostal<span class="sc">==</span><span class="st">"2815"</span>),<span class="st">'CodigoPostal'</span>] <span class="ot">&lt;-</span> <span class="st">"28105"</span></span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a>airbnb[<span class="fu">which</span>(airbnb<span class="sc">$</span>CodigoPostal<span class="sc">==</span><span class="st">""</span>),<span class="st">'CodigoPostal'</span>] <span class="ot">&lt;-</span> <span class="cn">NA</span></span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a>airbnb[<span class="fu">which</span>(airbnb<span class="sc">$</span>CodigoPostal<span class="sc">==</span><span class="st">"-"</span>),<span class="st">'CodigoPostal'</span>] <span class="ot">&lt;-</span> <span class="cn">NA</span></span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a>airbnb[<span class="fu">which</span>(airbnb<span class="sc">$</span>CodigoPostal<span class="sc">==</span><span class="st">"28"</span>),<span class="st">'CodigoPostal'</span>] <span class="ot">&lt;-</span> <span class="cn">NA</span></span>
<span id="cb15-7"><a href="#cb15-7" aria-hidden="true" tabindex="-1"></a>airbnb[<span class="fu">which</span>(airbnb<span class="sc">$</span>CodigoPostal<span class="sc">==</span><span class="st">"28051</span><span class="sc">\n</span><span class="st">28051"</span>),<span class="st">'CodigoPostal'</span>] <span class="ot">&lt;-</span> <span class="st">"28051"</span></span>
<span id="cb15-8"><a href="#cb15-8" aria-hidden="true" tabindex="-1"></a>airbnb[<span class="fu">which</span>(airbnb<span class="sc">$</span>CodigoPostal<span class="sc">==</span><span class="st">"28002</span><span class="sc">\n</span><span class="st">28002"</span>),<span class="st">'CodigoPostal'</span>] <span class="ot">&lt;-</span> <span class="st">"28002"</span></span>
<span id="cb15-9"><a href="#cb15-9" aria-hidden="true" tabindex="-1"></a>airbnb[<span class="fu">which</span>(airbnb<span class="sc">$</span>CodigoPostal<span class="sc">==</span><span class="st">"2804"</span>),<span class="st">'CodigoPostal'</span>] <span class="ot">&lt;-</span> <span class="st">"28040"</span></span>
<span id="cb15-10"><a href="#cb15-10" aria-hidden="true" tabindex="-1"></a>airbnb[<span class="fu">which</span>(airbnb<span class="sc">$</span>CodigoPostal<span class="sc">==</span><span class="st">"2805"</span>),<span class="st">'CodigoPostal'</span>] <span class="ot">&lt;-</span> <span class="st">"28050"</span></span>
<span id="cb15-11"><a href="#cb15-11" aria-hidden="true" tabindex="-1"></a>airbnb[<span class="fu">which</span>(airbnb<span class="sc">$</span>CodigoPostal<span class="sc">==</span><span class="st">"280013"</span>),<span class="st">'CodigoPostal'</span>] <span class="ot">&lt;-</span> <span class="st">"28013"</span></span>
<span id="cb15-12"><a href="#cb15-12" aria-hidden="true" tabindex="-1"></a>airbnb[<span class="sc">!</span><span class="fu">grepl</span>(<span class="st">"^28</span><span class="sc">\\</span><span class="st">d{3}$"</span>,airbnb<span class="sc">$</span>CodigoPostal), <span class="st">"CodigoPostal"</span>] <span class="ot">&lt;-</span> <span class="cn">NA</span></span>
<span id="cb15-13"><a href="#cb15-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-14"><a href="#cb15-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-15"><a href="#cb15-15" aria-hidden="true" tabindex="-1"></a><span class="do">##Actualizamos factor para no incluir valores modificados</span></span>
<span id="cb15-16"><a href="#cb15-16" aria-hidden="true" tabindex="-1"></a>airbnb<span class="sc">$</span>CodigoPostal <span class="ot">&lt;-</span> <span class="fu">factor</span>(airbnb<span class="sc">$</span>CodigoPostal)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"El listado de CodigoPostal después de limpieza es: </span><span class="sc">\n\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>El listado de CodigoPostal después de limpieza es: </code></pre>
</div>
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>airbnb<span class="sc">$</span>CodigoPostal <span class="sc">|&gt;</span> <span class="fu">table</span>(<span class="at">useNA=</span><span class="st">'always'</span>) <span class="sc">|&gt;</span> <span class="fu">sort</span>(<span class="at">decreasing =</span> <span class="cn">TRUE</span>) <span class="sc">|&gt;</span> <span class="fu">data.frame</span>() <span class="sc">|&gt;</span> <span class="fu">print.data.frame</span>(<span class="at">row.names =</span> <span class="cn">FALSE</span>) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  Var1 Freq
 28012 2060
 28004 1795
 28005 1194
 28013 1020
 28014  630
 28015  600
 28045  495
  &lt;NA&gt;  447
 28010  384
 28008  338
 28028  263
 28011  250
 28001  231
 28006  218
 28009  216
 28007  206
 28019  200
 28020  192
 28003  185
 28002  171
 28039  160
 28025  123
 28027  122
 28029  110
 28017  107
 28043  103
 28026   93
 28042   90
 28033   89
 28053   85
 28038   77
 28016   76
 28030   73
 28036   67
 28047   67
 28037   65
 28041   63
 28035   59
 28050   59
 28021   58
 28034   45
 28024   44
 28018   43
 28032   33
 28046   32
 28022   30
 28031   27
 28023   23
 28044   19
 28040   17
 28051   17
 28054   12
 28055   12
 28049    3
 28105    2
 28048    1
 28052    1
 28056    1
 28058    1
 28060    1
 28094    1
 28850    1</code></pre>
</div>
</div>
<p><strong>Una vez limpios los datos ¿Cuales son los códigos postales que tenemos?</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Hay "</span>, <span class="fu">length</span>(<span class="fu">unique</span>(airbnb<span class="sc">$</span>CodigoPostal)), <span class="st">" codigos postales distintos y son :"</span>,<span class="fu">paste</span>(<span class="fu">unique</span>(airbnb<span class="sc">$</span>CodigoPostal), <span class="at">collapse =</span> <span class="st">","</span>),<span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Hay  62  codigos postales distintos y son : 28004,28015,28013,28005,28012,28014,28045,NA,28007,28028,28009,28001,28006,28010,28002,28034,28050,28008,28011,28049,28038,28053,28047,28025,28019,28024,28016,28036,28046,28039,28020,28003,28029,28054,28041,28026,28058,28018,28030,28017,28027,28043,28033,28055,28021,28032,28037,28022,28042,28094,28035,28040,28031,28044,28105,28023,28051,28850,28048,28056,28060,28052 </code></pre>
</div>
</div>
<p><strong>¿Cuales son los 5 códigos postales con más entradas? ¿Y con menos? ¿Cuantas entradas tienen?</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>tabla_frecuencias <span class="ot">&lt;-</span> <span class="fu">table</span>(airbnb<span class="sc">$</span>CodigoPostal) <span class="sc">|&gt;</span> <span class="fu">sort</span>(<span class="at">decreasing =</span> <span class="cn">TRUE</span>) <span class="sc">|&gt;</span> <span class="fu">as.data.frame</span>()</span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(tabla_frecuencias) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"Barrio"</span>,<span class="st">"Entradas"</span>)</span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Los 5 códigos postales con más entradas son: </span><span class="sc">\n\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Los 5 códigos postales con más entradas son: </code></pre>
</div>
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print.data.frame</span>(tabla_frecuencias[<span class="dv">1</span><span class="sc">:</span><span class="dv">5</span>,],<span class="at">row.names =</span> <span class="cn">FALSE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> Barrio Entradas
  28012     2060
  28004     1795
  28005     1194
  28013     1020
  28014      630</code></pre>
</div>
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"</span><span class="sc">\n</span><span class="st">Los 5 códigos postales con menos entradas son: </span><span class="sc">\n\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Los 5 códigos postales con menos entradas son: </code></pre>
</div>
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a>tabla_frecuencias <span class="ot">&lt;-</span> tabla_frecuencias[<span class="fu">order</span>(tabla_frecuencias<span class="sc">$</span>Entradas),]</span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a><span class="fu">print.data.frame</span>(tabla_frecuencias[<span class="dv">1</span><span class="sc">:</span><span class="dv">5</span>,],<span class="at">row.names =</span> <span class="cn">FALSE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> Barrio Entradas
  28048        1
  28052        1
  28056        1
  28058        1
  28060        1</code></pre>
</div>
</div>
<p><strong>¿Cuales son los barrios que hay en el código postal 28012?</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a>barrios_cp_28012 <span class="ot">&lt;-</span> <span class="fu">unique</span>(airbnb[<span class="fu">which</span>(airbnb<span class="sc">$</span>CodigoPostal <span class="sc">==</span> <span class="st">"28012"</span>), <span class="st">"Barrio"</span>])</span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Los barrios que hay en el código postal 28012 son : </span><span class="sc">\n</span><span class="st">"</span>, <span class="fu">paste0</span>(barrios_cp_28012,<span class="at">collapse=</span><span class="st">","</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Los barrios que hay en el código postal 28012 son : 
 Sol,Acacias,Palos de Moguer,Embajadores,Cortes,Palacio,Universidad,Delicias,Arapiles,Atocha,Goya</code></pre>
</div>
</div>
<p><strong>¿Cuantas entradas hay en cada uno de esos barrios para el codigo postal 28012?</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a>entradas_barrios_cp_28012 <span class="ot">&lt;-</span> <span class="fu">table</span>(<span class="fu">droplevels</span>(airbnb[<span class="fu">which</span>(airbnb<span class="sc">$</span>CodigoPostal <span class="sc">==</span> <span class="st">"28012"</span>), <span class="st">"Barrio"</span>])) <span class="sc">|&gt;</span> <span class="fu">sort</span>(<span class="at">decreasing =</span> <span class="cn">TRUE</span>) <span class="sc">|&gt;</span> <span class="fu">as.data.frame</span>() </span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(entradas_barrios_cp_28012) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"Barrio"</span>,<span class="st">"Entradas"</span>)</span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"El codigo postal 28012 tienes por barrios las siguientes entradas: </span><span class="sc">\n\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>El codigo postal 28012 tienes por barrios las siguientes entradas: </code></pre>
</div>
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print.data.frame</span>(entradas_barrios_cp_28012,<span class="at">row.names =</span> <span class="cn">FALSE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>          Barrio Entradas
     Embajadores     1449
             Sol      301
          Cortes      216
 Palos de Moguer       46
         Palacio       27
         Acacias       13
     Universidad        4
        Arapiles        1
          Atocha        1
        Delicias        1
            Goya        1</code></pre>
</div>
</div>
<p><strong>¿Cuantos barrios hay en todo el dataset airbnb? ¿Cuales son?</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Obtener los barrios únicos del dataset airbnb</span></span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a>barrios_unicos <span class="ot">&lt;-</span> <span class="fu">unique</span>(airbnb<span class="sc">$</span>Barrio)</span>
<span id="cb36-3"><a href="#cb36-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-4"><a href="#cb36-4" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"El dataset airbnb tienes: "</span>, <span class="fu">length</span>(barrios_unicos), <span class="st">" barrios únicos </span><span class="sc">\n</span><span class="st">Lista de barrios únicos:</span><span class="sc">\n</span><span class="st">"</span>,<span class="fu">paste</span>(barrios_unicos, <span class="at">collapse =</span> <span class="st">","</span>),<span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>El dataset airbnb tienes:  125  barrios únicos 
Lista de barrios únicos:
 Universidad,Sol,Imperial,Acacias,Chopera,Delicias,Palos de Moguer,Embajadores,Cortes,Atocha,Pacífico,Adelfas,Estrella,Ibiza,Jerónimos,Niño Jesús,Palacio,Justicia,Recoletos,Goya,Fuente del Berro,Arapiles,Trafalgar,Almagro,Guindalera,Lista,Castellana,El Viso,Prosperidad,Valverde,Casa de Campo,El Goloso,Numancia,Cármenes,Puerta del Angel,Lucero,Aluche,San Isidro,Campamento,Comillas,Opañel,Vista Alegre,Ciudad Jardín,Hispanoamérica,Nueva España,Castilla,Bellas Vistas,Cuatro Caminos,Castillejos,Vallehermoso,Almenara,Valdeacederas,Berruguete,Gaztambide,Rios Rosas,Peñagrande,Argüelles,Puerta Bonita,Buenavista,Abrantes,Orcasur,San Fermín,Almendrales,Pradolongo,Portazgo,Entrevías,San Diego,Palomeras Bajas,Fontarrón,Vinateros,Ventas,Pueblo Nuevo,Quintana,Concepción,San Juan Bautista,Costillares,Piovera,Canillas,Pinar del Rey,Apostol Santiago,San Andrés,Valdefuentes,Butarque,Los Angeles,Casco Histórico de Vicálvaro,Simancas,Rejas,Salvador,Casco Histórico de Barajas,Pilar,La Paz,Mirasierra,Ciudad Universitaria,Moscardó,Palomeras Sureste,Marroquina,Media Legua,Los Rosales,Casco Histórico de Vallecas,Timón,Corralejos,Cuatro Vientos,Colina,San Cristobal,Alameda de Osuna,Aeropuerto,Palomas,Zofío,Aguilas,Legazpi,Fuentelareina,Aravaca,Ambroz,Canillejas,Valdezarza,Amposta,San Pascual,Santa Eugenia,Arcos,Rosas,Valdemarín,El Plantío,Hellín,Pavones,Orcasitas </code></pre>
</div>
</div>
<p><strong>¿Cuales son los 5 barrios que tienen mayor número entradas?</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a>barrios_aparicion <span class="ot">&lt;-</span> <span class="fu">table</span>(airbnb<span class="sc">$</span>Barrio)<span class="sc">|&gt;</span> <span class="fu">sort</span>(<span class="at">decreasing =</span> <span class="cn">TRUE</span>)<span class="sc">|&gt;</span> <span class="fu">as.data.frame</span>()</span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(barrios_aparicion) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"Barrio"</span>,<span class="st">"Entradas"</span>)</span>
<span id="cb38-3"><a href="#cb38-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-4"><a href="#cb38-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Mostrar los 5 barrios con mayor número de entradas</span></span>
<span id="cb38-5"><a href="#cb38-5" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Los 5 barrios con mayor número de entradas en el dataset airbnb son:</span><span class="sc">\n\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Los 5 barrios con mayor número de entradas en el dataset airbnb son:</code></pre>
</div>
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print.data.frame</span>(barrios_aparicion[<span class="dv">1</span><span class="sc">:</span><span class="dv">5</span>,],<span class="at">row.names =</span> <span class="cn">FALSE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>      Barrio Entradas
 Embajadores     1844
 Universidad     1358
     Palacio     1083
         Sol      940
    Justicia      785</code></pre>
</div>
</div>
<p><strong>¿Cuantos Tipos de Alquiler diferentes hay? ¿Cuales son? ¿Cuantas entradas en el dataframe hay por cada tipo?</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Contar el número de entradas por cada tipo de alquiler utilizando la función length en table</span></span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a>tipos_alquiler <span class="ot">&lt;-</span> <span class="fu">unique</span>(airbnb<span class="sc">$</span>TipoAlquiler)</span>
<span id="cb42-3"><a href="#cb42-3" aria-hidden="true" tabindex="-1"></a>tipos_alquiler_entradas  <span class="ot">&lt;-</span> <span class="fu">table</span>(airbnb<span class="sc">$</span>TipoAlquiler)<span class="sc">|&gt;</span> <span class="fu">sort</span>( <span class="at">decreasing =</span> <span class="cn">TRUE</span>)<span class="sc">|&gt;</span> <span class="fu">as.data.frame</span>()</span>
<span id="cb42-4"><a href="#cb42-4" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(tipos_alquiler_entradas) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"Tipo apartamento"</span>,<span class="st">"Entradas"</span>)</span>
<span id="cb42-5"><a href="#cb42-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-6"><a href="#cb42-6" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Hay "</span>,<span class="fu">length</span>(tipos_alquiler),<span class="st">" tipos de alquiler diferentes. </span><span class="sc">\n\n</span><span class="st">Los tipos de  alquileres son :"</span>,<span class="fu">paste</span>(tipos_alquiler,<span class="at">collapse=</span><span class="st">" , "</span>),<span class="st">"</span><span class="sc">\n\n</span><span class="st">La entradas que hay por cada tipo de alquiler son: </span><span class="sc">\n\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Hay  3  tipos de alquiler diferentes. 

Los tipos de  alquileres son : Private room , Entire home/apt , Shared room 

La entradas que hay por cada tipo de alquiler son: </code></pre>
</div>
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print.data.frame</span>(tipos_alquiler_entradas,<span class="at">row.names=</span><span class="cn">FALSE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> Tipo apartamento Entradas
  Entire home/apt     7903
     Private room     5113
      Shared room      191</code></pre>
</div>
</div>
<p><strong>Muestra el diagrama de cajas del precio para cada uno de los diferentes Tipos de Alquiler</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Cargar la librería necesaria para el gráfico de cajas</span></span>
<span id="cb46-2"><a href="#cb46-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb46-3"><a href="#cb46-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb46-4"><a href="#cb46-4" aria-hidden="true" tabindex="-1"></a><span class="co">#Generar el diagrama de cajas por tipo de alquiler y de cada color pintamos el tipo de alquiler.</span></span>
<span id="cb46-5"><a href="#cb46-5" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data=</span>airbnb, <span class="fu">aes</span>(<span class="at">x=</span>TipoAlquiler, <span class="at">y=</span>Precio, <span class="at">color=</span>TipoAlquiler))<span class="sc">+</span><span class="fu">geom_boxplot</span>(<span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Bartolome_Flores_Vciaria-PracticaFinal_files/figure-html/unnamed-chunk-18-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p><strong>Cual es el precio medio de alquiler de cada uno, la diferencia que hay ¿es estadísticamente significativa? ¿Con que test lo comprobarías?</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a>tipos_alquiler <span class="ot">&lt;-</span><span class="fu">unique</span>(airbnb[<span class="st">"TipoAlquiler"</span>])</span>
<span id="cb47-2"><a href="#cb47-2" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span>(alquiler <span class="cf">in</span> <span class="fu">t</span>(tipos_alquiler)){</span>
<span id="cb47-3"><a href="#cb47-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">cat</span>(<span class="st">"El precio medio de alquiler en "</span>, alquiler ,<span class="st">" es: "</span> , <span class="fu">mean</span>(airbnb[<span class="fu">which</span>(airbnb<span class="sc">$</span>TipoAlquiler <span class="sc">==</span> alquiler),<span class="st">"Precio"</span>],<span class="at">na.rm=</span><span class="cn">TRUE</span>) ,<span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span>
<span id="cb47-4"><a href="#cb47-4" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>El precio medio de alquiler en  Private room  es:  34.25514 
El precio medio de alquiler en  Entire home/apt  es:  87.29661 
El precio medio de alquiler en  Shared room  es:  29.8534 </code></pre>
</div>
</div>
<p>Para comprobar si son estadísticamente significativas hay que hacer los siguientes pasos:</p>
<p>Como tenemos 3 tipos de alquiler distintos , primero tenemos que comprobar si siguen una distribución gaussiana y para ello tenemos que realizarle a cada tipo de alquiler el Shapiro-Wilk. No podemos usar t de Student porque es solo para dos grupos.</p>
<p>Las hipótesis que seguiremos para cada una de ellas será:</p>
<p><span class="math inline">\(H_0\)</span>: La variable presenta una distribución normal</p>
<p><span class="math inline">\(H_1\)</span>: La variable presenta una distribución no normal</p>
<p>La decisión que tomaremos después de aplicar el test Shapiro será:</p>
<p>p-valor &gt; 0.05 No rechazar H0 (El tipo de alquiler presenta una distribución normal)</p>
<p>p-valor &lt; 0.05 Rechazar H0 (El tipo de alquiler no presenta una distribución normal)</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span>(alquiler <span class="cf">in</span> <span class="fu">levels</span>(airbnb<span class="sc">$</span>TipoAlquiler)){</span>
<span id="cb49-2"><a href="#cb49-2" aria-hidden="true" tabindex="-1"></a>  precios_alquiler <span class="ot">&lt;-</span> airbnb<span class="sc">$</span>Precio[airbnb<span class="sc">$</span>TipoAlquiler<span class="sc">==</span>alquiler]</span>
<span id="cb49-3"><a href="#cb49-3" aria-hidden="true" tabindex="-1"></a>  <span class="cf">if</span>(<span class="fu">length</span>(precios_alquiler)<span class="sc">&gt;</span><span class="dv">5000</span>){</span>
<span id="cb49-4"><a href="#cb49-4" aria-hidden="true" tabindex="-1"></a>    <span class="co">#El test de Shapiro en R solo funciona si hay entre 3 y 5000 entradas , por lo cual si en el caso que haya mas de 5000 entradas hay que hacer un sample para obtener solo 5000</span></span>
<span id="cb49-5"><a href="#cb49-5" aria-hidden="true" tabindex="-1"></a>    precios_alquiler<span class="ot">&lt;-</span> <span class="fu">sample</span>(precios_alquiler,<span class="dv">5000</span>, <span class="at">replace =</span> <span class="cn">TRUE</span>)</span>
<span id="cb49-6"><a href="#cb49-6" aria-hidden="true" tabindex="-1"></a>  }</span>
<span id="cb49-7"><a href="#cb49-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">cat</span>(<span class="st">"Tipo alquiler "</span>,alquiler,<span class="st">" p-value = "</span> ,<span class="fu">shapiro.test</span>(precios_alquiler)<span class="sc">$</span>p.value,<span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span>
<span id="cb49-8"><a href="#cb49-8" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Tipo alquiler  Entire home/apt  p-value =  4.67477e-70 
Tipo alquiler  Private room  p-value =  1.817303e-85 
Tipo alquiler  Shared room  p-value =  4.516721e-24 </code></pre>
</div>
</div>
<p>Como el p valor es menor que 0.05 en los tres casos se rechaza la hipótesis nula (H0), por lo tanto, los precios según el tipo de alquiler no sigue una distribución normal.</p>
<p>Ya que sabemos que no siguen la misma distribución gaussiana procederemos a usar el test para aquellos grupos que no siguen la misma distribución y es el Kruskal-Wallis . No usaremos ANOVA test Welch porque no siguen una distribución gaussiana.</p>
<p>Las hipótesis que seguiremos para cada una de ellas será:</p>
<p><span class="math inline">\(H_0\)</span>: Los tipos de alquiler tienen misma media.</p>
<p><span class="math inline">\(H_1\)</span>: Los tipos de alquiler tienen diferente media al menos unos de ellos.</p>
<p>La decisión que tomaremos después de aplicar el test Shapiro será:</p>
<p>p-valor &gt; 0.05 No rechazar H0 (tomas las medias son similares)</p>
<p>p-valor &lt; 0.05 Rechazar H0 (hay al menos una que no es similar a las demás)</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a><span class="fu">kruskal.test</span>(Precio <span class="sc">~</span> TipoAlquiler, <span class="at">data=</span>airbnb)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Kruskal-Wallis rank sum test

data:  Precio by TipoAlquiler
Kruskal-Wallis chi-squared = 7235.6, df = 2, p-value &lt; 2.2e-16</code></pre>
</div>
</div>
<p>Como el p-valor (2e-16) nos da muy inferior a 0.05 podemos rechazar la hipótesis nula H0 , por lo tanto, los precios según el tipo de alquiler hay al menos uno que no tiene la misma media.</p>
<p><strong>Filtra el dataframe cuyos tipo de alquiler sea ‘Entire home/apt’ y guardalo en un dataframe llamado <em>airbnb_entire</em>. Estas serán las entradas que tienen un alquiler del piso completo.</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb53"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a>airbnb_entire <span class="ot">&lt;-</span>airbnb[<span class="fu">which</span>(airbnb<span class="sc">$</span>TipoAlquiler <span class="sc">==</span> <span class="st">"Entire home/apt"</span>), ] </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><strong>¿Cuales son los 5 barrios que tienen un mayor número de apartamentos enteros en alquiler? Nota: Mirar solo en airbnb_entire. A partir de este punto y hasta que se diga lo contrario partiremos de airbnb_entire.</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb54"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a>barrios_por_entradas<span class="ot">&lt;-</span> <span class="fu">table</span>(airbnb_entire<span class="sc">$</span>Barrio)<span class="sc">|&gt;</span> <span class="fu">sort</span>(<span class="at">decreasing =</span> <span class="cn">TRUE</span>)<span class="sc">|&gt;</span> <span class="fu">as.data.frame</span>()</span>
<span id="cb54-2"><a href="#cb54-2" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(barrios_por_entradas) <span class="ot">&lt;-</span><span class="fu">c</span>(<span class="st">"Barrio"</span>,<span class="st">"Entradas"</span>)</span>
<span id="cb54-3"><a href="#cb54-3" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Los 5 barrios que tienen un mayor número de apartamentos enteros en alquiler son: </span><span class="sc">\n\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Los 5 barrios que tienen un mayor número de apartamentos enteros en alquiler son: </code></pre>
</div>
<div class="sourceCode cell-code" id="cb56"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print.data.frame</span>(barrios_por_entradas[<span class="dv">1</span><span class="sc">:</span><span class="dv">5</span>,],<span class="at">row.names=</span><span class="cn">FALSE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>      Barrio Entradas
 Embajadores     1228
 Universidad      984
     Palacio      769
         Sol      701
      Cortes      574</code></pre>
</div>
</div>
<p><strong>¿Cuales son los 5 barrios que tienen un mayor precio medio de alquiler para apartamentos enteros (es decir, del dataframe airbnb_entire)?</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb58"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb58-1"><a href="#cb58-1" aria-hidden="true" tabindex="-1"></a>barrios_por_precio_medio <span class="ot">&lt;-</span> <span class="fu">aggregate</span>(Precio <span class="sc">~</span> Barrio, <span class="at">FUN =</span> mean, <span class="at">data =</span> airbnb_entire)</span>
<span id="cb58-2"><a href="#cb58-2" aria-hidden="true" tabindex="-1"></a>barrios_por_precio_medio <span class="ot">&lt;-</span> barrios_por_precio_medio[<span class="fu">order</span>(<span class="sc">-</span>barrios_por_precio_medio<span class="sc">$</span>Precio),]</span>
<span id="cb58-3"><a href="#cb58-3" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Los 5 barrios que tienen un mayor precio medio de alquiler para apartamentos enteros son: </span><span class="sc">\n\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Los 5 barrios que tienen un mayor precio medio de alquiler para apartamentos enteros son: </code></pre>
</div>
<div class="sourceCode cell-code" id="cb60"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb60-1"><a href="#cb60-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print.data.frame</span>(barrios_por_precio_medio[<span class="dv">1</span><span class="sc">:</span><span class="dv">5</span>,<span class="fu">c</span>(<span class="st">"Barrio"</span>,<span class="st">"Precio"</span>)],<span class="at">row.names =</span> <span class="cn">FALSE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>        Barrio   Precio
       Palomas 309.7500
 Fuentelareina 180.0000
     Recoletos 161.9254
    El Plantío 150.0000
    Castellana 141.3889</code></pre>
</div>
</div>
<p><strong>¿Cuantos apartamentos hay en cada uno de esos barrios?</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb62"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb62-1"><a href="#cb62-1" aria-hidden="true" tabindex="-1"></a>vector_barrios_precio_medio <span class="ot">&lt;-</span> barrios_por_precio_medio[<span class="dv">1</span><span class="sc">:</span><span class="dv">5</span>, <span class="st">"Barrio"</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb63"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb63-1"><a href="#cb63-1" aria-hidden="true" tabindex="-1"></a>top_5_precio_medio <span class="ot">&lt;-</span> <span class="fu">subset</span>(airbnb_entire, Barrio <span class="sc">%in%</span> vector_barrios_precio_medio) </span>
<span id="cb63-2"><a href="#cb63-2" aria-hidden="true" tabindex="-1"></a>top_5_precio_medio <span class="ot">&lt;-</span> <span class="fu">table</span>(<span class="fu">droplevels</span>(top_5_precio_medio<span class="sc">$</span>Barrio)) <span class="sc">|&gt;</span> <span class="fu">sort</span>(<span class="at">decreasing =</span> <span class="cn">TRUE</span>)<span class="sc">|&gt;</span> <span class="fu">as.data.frame</span>()</span>
<span id="cb63-3"><a href="#cb63-3" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(top_5_precio_medio) <span class="ot">&lt;-</span><span class="fu">c</span>(<span class="st">"Barrio"</span>,<span class="st">"Entradas"</span>)</span>
<span id="cb63-4"><a href="#cb63-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-5"><a href="#cb63-5" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"En cada uno de esos barrios con mayor precio medio por barrio hay:</span><span class="sc">\n\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>En cada uno de esos barrios con mayor precio medio por barrio hay:</code></pre>
</div>
<div class="sourceCode cell-code" id="cb65"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb65-1"><a href="#cb65-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print.data.frame</span>(top_5_precio_medio[<span class="dv">1</span><span class="sc">:</span><span class="dv">5</span>,],<span class="at">row.names=</span><span class="cn">FALSE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>        Barrio Entradas
     Recoletos      135
    Castellana       73
       Palomas        4
 Fuentelareina        2
    El Plantío        1</code></pre>
</div>
</div>
<p><strong>Mostrar una dataframe con el nombre del barrio, el precio y el número de entradas.</strong></p>
<p>Ayuda: Podeis crear un nuevo dataframe con las columnas “Barrio” y “Freq” que contenga el número de entradas en cada barrio y hacer un merge con el dataframe del punto anterior.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb67"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb67-1"><a href="#cb67-1" aria-hidden="true" tabindex="-1"></a>barrio_resumen <span class="ot">&lt;-</span> <span class="fu">merge</span>(barrios_por_precio_medio,barrios_por_entradas, <span class="at">by =</span> <span class="st">"Barrio"</span>,<span class="at">all=</span><span class="cn">TRUE</span>)</span>
<span id="cb67-2"><a href="#cb67-2" aria-hidden="true" tabindex="-1"></a>barrio_resumen<span class="sc">$</span>Precio <span class="ot">&lt;-</span> <span class="fu">round</span>(barrio_resumen<span class="sc">$</span>Precio,<span class="dv">2</span>)</span>
<span id="cb67-3"><a href="#cb67-3" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(barrio_resumen) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"Barrio"</span>,<span class="st">"Precio"</span>,<span class="st">"Entradas"</span>)</span>
<span id="cb67-4"><a href="#cb67-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb67-5"><a href="#cb67-5" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Dataframe con nombre de barrio, precio medio y número de entradas :</span><span class="sc">\n\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Dataframe con nombre de barrio, precio medio y número de entradas :</code></pre>
</div>
<div class="sourceCode cell-code" id="cb69"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb69-1"><a href="#cb69-1" aria-hidden="true" tabindex="-1"></a>barrio_resumen</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                          Barrio Precio Entradas
1                       Abrantes  46.00        3
2                        Acacias  68.16       61
3                        Adelfas  68.73       33
4                     Aeropuerto  38.00        2
5                        Aguilas  54.50        2
6               Alameda de Osuna 138.75        4
7                        Almagro 109.19       97
8                       Almenara  65.68       25
9                    Almendrales  77.50       18
10                        Aluche  55.89        9
11                        Ambroz  34.50        2
12                       Amposta     NA        0
13              Apostol Santiago  96.60        5
14                      Arapiles  69.62       98
15                       Aravaca  66.33        9
16                         Arcos 100.50        4
17                     Argüelles  89.57      143
18                        Atocha  71.44        9
19                 Bellas Vistas  51.78       45
20                    Berruguete  53.86       35
21                    Buenavista  57.92       12
22                      Butarque  42.00        1
23                    Campamento  45.56        9
24                      Canillas 105.80       15
25                    Canillejas  91.67        3
26                      Cármenes  78.00        8
27                 Casa de Campo  98.85       41
28    Casco Histórico de Barajas 141.25        8
29   Casco Histórico de Vallecas  61.11       18
30  Casco Histórico de Vicálvaro  73.88        8
31                    Castellana 141.39       73
32                      Castilla  68.67       21
33                   Castillejos  88.70       44
34                       Chopera  55.03       34
35                 Ciudad Jardín  87.62       32
36          Ciudad Universitaria 138.31       13
37                        Colina  64.43        7
38                      Comillas  56.67       21
39                    Concepción  61.94       16
40                    Corralejos     NA        0
41                        Cortes  94.39      574
42                   Costillares  95.08       13
43                Cuatro Caminos  76.65       72
44                Cuatro Vientos     NA        0
45                      Delicias  66.00       51
46                     El Goloso     NA        0
47                    El Plantío 150.00        1
48                       El Viso  76.38       24
49                   Embajadores  73.70     1228
50                     Entrevías  56.25        4
51                      Estrella  92.67        3
52                     Fontarrón  51.80        5
53              Fuente del Berro  70.32       38
54                 Fuentelareina 180.00        2
55                    Gaztambide  86.69       61
56                          Goya 111.34      142
57                    Guindalera  76.99       82
58                        Hellín  42.00        1
59                Hispanoamérica 104.44       52
60                         Ibiza 102.62       64
61                      Imperial  61.43       42
62                     Jerónimos 131.82       62
63                      Justicia  98.25      534
64                        La Paz  65.33        3
65                       Legazpi  79.29       14
66                         Lista  90.11       72
67                   Los Angeles  69.40        5
68                   Los Rosales  75.00        2
69                        Lucero  68.31       13
70                    Marroquina  50.00        2
71                   Media Legua  72.10       10
72                    Mirasierra 101.29        7
73                      Moscardó  56.06       18
74                    Niño Jesús  89.23       15
75                  Nueva España 127.31       42
76                      Numancia  60.59       34
77                        Opañel  51.60       10
78                     Orcasitas     NA        0
79                       Orcasur  45.00        1
80                      Pacífico  89.73       62
81                       Palacio  93.31      769
82                       Palomas 309.75        4
83               Palomeras Bajas  61.10       10
84             Palomeras Sureste  31.50        4
85               Palos de Moguer  73.32      135
86                       Pavones  48.00        1
87                    Peñagrande 127.64       11
88                         Pilar  62.50       10
89                 Pinar del Rey  79.89        9
90                       Piovera  85.00        3
91                      Portazgo  55.00        1
92                    Pradolongo  61.33        3
93                   Prosperidad  79.47       49
94                  Pueblo Nuevo  67.46       13
95                 Puerta Bonita  88.00       14
96              Puerta del Angel  59.68       77
97                      Quintana  65.00       17
98                     Recoletos 161.93      135
99                         Rejas  64.18       11
100                   Rios Rosas  83.00       60
101                        Rosas     NA        0
102                     Salvador  66.40        5
103                   San Andrés  50.92       12
104                San Cristobal  56.50        2
105                    San Diego  44.34       32
106                   San Fermín  63.50        8
107                   San Isidro  76.10       39
108            San Juan Bautista  75.54       13
109                  San Pascual  72.43        7
110                Santa Eugenia  47.00        2
111                     Simancas  57.14       21
112                          Sol 100.75      701
113                        Timón  72.20        5
114                    Trafalgar  98.58      223
115                  Universidad  79.40      984
116                Valdeacederas  67.36       25
117                 Valdefuentes  84.25       24
118                   Valdemarín  70.50        2
119                   Valdezarza  53.33        3
120                 Vallehermoso  92.39       33
121                     Valverde  71.58       19
122                       Ventas  50.04       26
123                    Vinateros 102.50        2
124                 Vista Alegre  59.45       22
125                        Zofío  48.00        4</code></pre>
</div>
</div>
<p><strong>Partiendo del dataframe anterior, muestra los 5 barrios con mayor precio, pero que tengan más de 100 entradas de alquiler.</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb71"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb71-1"><a href="#cb71-1" aria-hidden="true" tabindex="-1"></a>top_5_mayor_precio_mas_100_entrada <span class="ot">&lt;-</span> <span class="fu">subset</span>(barrio_resumen,Entradas <span class="sc">&gt;=</span> <span class="dv">100</span>)</span>
<span id="cb71-2"><a href="#cb71-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb71-3"><a href="#cb71-3" aria-hidden="true" tabindex="-1"></a>top_5_mayor_precio_mas_100_entrada <span class="ot">&lt;-</span> top_5_mayor_precio_mas_100_entrada[<span class="fu">order</span>(<span class="sc">-</span>top_5_mayor_precio_mas_100_entrada<span class="sc">$</span>Precio),]</span>
<span id="cb71-4"><a href="#cb71-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb71-5"><a href="#cb71-5" aria-hidden="true" tabindex="-1"></a>vector_100_entradas <span class="ot">&lt;-</span> top_5_mayor_precio_mas_100_entrada[<span class="dv">1</span><span class="sc">:</span><span class="dv">5</span>,<span class="st">"Barrio"</span>]</span>
<span id="cb71-6"><a href="#cb71-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb71-7"><a href="#cb71-7" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Los 5 barrios con mayor precio medio de alquiler son:</span><span class="sc">\n\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Los 5 barrios con mayor precio medio de alquiler son:</code></pre>
</div>
<div class="sourceCode cell-code" id="cb73"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb73-1"><a href="#cb73-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print.data.frame</span>(top_5_mayor_precio_mas_100_entrada[<span class="dv">1</span><span class="sc">:</span><span class="dv">5</span>,],<span class="at">row.names=</span><span class="cn">FALSE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>    Barrio Precio Entradas
 Recoletos 161.93      135
      Goya 111.34      142
       Sol 100.75      701
 Trafalgar  98.58      223
  Justicia  98.25      534</code></pre>
</div>
</div>
<p><strong>Dibuja el diagrama de densidad de distribución de los diferentes precios. Serían 5 gráficas, una por cada barrio.</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb75"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb75-1"><a href="#cb75-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Pìntandolo en el mismo gráfico</span></span>
<span id="cb75-2"><a href="#cb75-2" aria-hidden="true" tabindex="-1"></a>barrio_a_dibujar <span class="ot">&lt;-</span> <span class="fu">subset</span>(airbnb_entire,Barrio <span class="sc">%in%</span> vector_100_entradas)</span>
<span id="cb75-3"><a href="#cb75-3" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(barrio_a_dibujar,<span class="fu">aes</span>(<span class="at">x=</span>Precio,<span class="at">color=</span>Barrio))<span class="sc">+</span></span>
<span id="cb75-4"><a href="#cb75-4" aria-hidden="true" tabindex="-1"></a><span class="fu">geom_density</span>(<span class="at">na.rm =</span> <span class="cn">FALSE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 1 rows containing non-finite values (`stat_density()`).</code></pre>
</div>
<div class="cell-output-display">
<p><img src="Bartolome_Flores_Vciaria-PracticaFinal_files/figure-html/unnamed-chunk-29-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p><strong>Calcula el tamaño medio, en metros cuadrados, para los 5 barrios anteriores y muestralo en el mismo dataframe junto con el precio y número de entradas</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb77"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb77-1"><a href="#cb77-1" aria-hidden="true" tabindex="-1"></a>barrios_por_metros_cuadrados_medio <span class="ot">&lt;-</span> <span class="fu">aggregate</span>(MetrosCuadrados <span class="sc">~</span> Barrio, <span class="at">FUN =</span> mean, <span class="at">data =</span> airbnb_entire)</span>
<span id="cb77-2"><a href="#cb77-2" aria-hidden="true" tabindex="-1"></a>barrio_resumen <span class="ot">&lt;-</span> <span class="fu">merge</span>(barrio_resumen,barrios_por_metros_cuadrados_medio, <span class="at">by =</span> <span class="st">"Barrio"</span>,<span class="at">all=</span><span class="cn">TRUE</span>)</span>
<span id="cb77-3"><a href="#cb77-3" aria-hidden="true" tabindex="-1"></a>barrio_resumen<span class="sc">$</span>MetrosCuadrados <span class="ot">&lt;-</span> <span class="fu">round</span>(barrio_resumen<span class="sc">$</span>MetrosCuadrados,<span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb78"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb78-1"><a href="#cb78-1" aria-hidden="true" tabindex="-1"></a>barrio_resumen_ <span class="ot">&lt;-</span> <span class="fu">subset</span>(barrio_resumen, Barrio <span class="sc">%in%</span> vector_100_entradas)</span>
<span id="cb78-2"><a href="#cb78-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb78-3"><a href="#cb78-3" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Los barrios con más de 100 entradas junto a su precio medio y media de metros cuadrados:</span><span class="sc">\n\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Los barrios con más de 100 entradas junto a su precio medio y media de metros cuadrados:</code></pre>
</div>
<div class="sourceCode cell-code" id="cb80"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb80-1"><a href="#cb80-1" aria-hidden="true" tabindex="-1"></a>barrio_resumen_</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       Barrio Precio Entradas MetrosCuadrados
56       Goya 111.34      142           51.69
63   Justicia  98.25      534           28.53
98  Recoletos 161.93      135           26.66
112       Sol 100.75      701           45.62
114 Trafalgar  98.58      223           29.30</code></pre>
</div>
</div>
<p><strong>Dibuja el diagrama de densidad de distribución de los diferentes tamaños de apartamentos. Serían 5 gráficas, una por cada barrio.</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb82"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb82-1"><a href="#cb82-1" aria-hidden="true" tabindex="-1"></a>barrio_a_dibujar <span class="ot">&lt;-</span> <span class="fu">subset</span>(airbnb_entire,Barrio <span class="sc">%in%</span> vector_100_entradas)</span>
<span id="cb82-2"><a href="#cb82-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(barrio_a_dibujar,<span class="fu">aes</span>(<span class="at">x=</span>MetrosCuadrados,<span class="at">color=</span>Barrio))<span class="sc">+</span></span>
<span id="cb82-3"><a href="#cb82-3" aria-hidden="true" tabindex="-1"></a><span class="fu">geom_density</span>(<span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Bartolome_Flores_Vciaria-PracticaFinal_files/figure-html/unnamed-chunk-32-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p><strong>Esta claro que las medias de metros cuadrados de cada uno de estos 5 barrios parecen ser diferentes, pero ¿son estadísticamente diferentes? ¿Que test habría que usar para comprobarlo?</strong></p>
<p>Para comprobar si son estadísticamente significativas hay que hacer los siguientes pasos:</p>
<p>Como tenemos 5 barrios , primero tenemos que comprobar si siguen una distribución gaussiana y para ello tenemos que realizarle a cada tipo de alquiler el Shapiro-Wilk. No podemos usar t de Student porque es solo para dos grupos.</p>
<p>Las hipótesis que seguiremos para cada una de ellas será:</p>
<p>$H_0$: La variable presenta una distribución normal</p>
<p>$H_1$: La variable presenta una distribución no normal</p>
<p>La decisión que tomaremos después de aplicar el test Shapiro será:</p>
<p>p-valor &gt; 0.05 No rechazar H0 (El tipo de alquiler presenta una distribución normal)</p>
<p>p-valor &lt; 0.05 Rechazar H0 (El tipo de alquiler no presenta una distribución normal)</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb83"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb83-1"><a href="#cb83-1" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span>(barrio <span class="cf">in</span> top_5_mayor_precio_mas_100_entrada[<span class="dv">1</span><span class="sc">:</span><span class="dv">5</span>,<span class="st">"Barrio"</span>]){</span>
<span id="cb83-2"><a href="#cb83-2" aria-hidden="true" tabindex="-1"></a>  metros_cuadrados <span class="ot">&lt;-</span> airbnb_entire<span class="sc">$</span>Precio[airbnb_entire<span class="sc">$</span>Barrio<span class="sc">==</span>barrio]</span>
<span id="cb83-3"><a href="#cb83-3" aria-hidden="true" tabindex="-1"></a>  <span class="cf">if</span>(<span class="fu">length</span>(metros_cuadrados)<span class="sc">&gt;</span><span class="dv">5000</span>){</span>
<span id="cb83-4"><a href="#cb83-4" aria-hidden="true" tabindex="-1"></a>    metros_cuadrados<span class="ot">&lt;-</span> <span class="fu">sample</span>(precios_alquiler,<span class="dv">5000</span>, <span class="at">replace =</span> <span class="cn">TRUE</span>)</span>
<span id="cb83-5"><a href="#cb83-5" aria-hidden="true" tabindex="-1"></a>  }</span>
<span id="cb83-6"><a href="#cb83-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">cat</span>(<span class="st">"Barrio "</span>,barrio,<span class="st">" p-value = "</span> ,<span class="fu">shapiro.test</span>(metros_cuadrados)<span class="sc">$</span>p.value,<span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span>
<span id="cb83-7"><a href="#cb83-7" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Barrio  Recoletos  p-value =  2.800346e-13 
Barrio  Goya  p-value =  2.76798e-11 
Barrio  Sol  p-value =  6.822961e-30 
Barrio  Trafalgar  p-value =  5.989247e-17 
Barrio  Justicia  p-value =  6.685769e-32 </code></pre>
</div>
</div>
<p>Como el p valor es menor que 0.05 en los cinco casos se rechaza la hipótesis nula (H0), por lo tanto, la media de los metros cuadrados no sigue una distribución normal.</p>
<p>Ya que sabemos que no siguen la misma distribución gaussiana procederemos a usar el test para aquellos grupos que no siguen la misma distribución y es el Kruskal-Wallis . No usaremos ANOVA test Welch porque no siguen una distribución gaussiana.</p>
<p>Las hipótesis que seguiremos para cada una de ellas será:</p>
<p>$H_0$: La media de los metros cuadrados por barrio tienen misma media.</p>
<p>$H_1$: La media de los metros cuadrados por barrio tienen diferente media al menos unos de ellos.</p>
<p>La decisión que tomaremos después de aplicar el test Shapiro será</p>
<p>p-valor &gt; 0.05 No rechazar H0 (tomas las medias son similares)</p>
<p>p-valor &lt; 0.05 Rechazar H0 (hay al menos una que no es similar a las demás)</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb85"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb85-1"><a href="#cb85-1" aria-hidden="true" tabindex="-1"></a><span class="fu">kruskal.test</span>(MetrosCuadrados <span class="sc">~</span> Barrio, <span class="at">data=</span>airbnb_entire)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Kruskal-Wallis rank sum test

data:  MetrosCuadrados by Barrio
Kruskal-Wallis chi-squared = 78.411, df = 55, p-value = 0.02077</code></pre>
</div>
</div>
<p>Como el p-valor (0.02077) nos da inferior a 0.05 podemos rechazar la hipótesis nula H0 , por lo tanto, la media de los metros cuadrados por barrio hay al menos uno que no tiene la misma media.</p>
<p><strong>Para únicamente los pisos de alquiler en el barrio de Sol:</strong></p>
<p><strong><code>barrio_sol&lt;-subset(airbnb_entire,Barrio=="Sol")</code></strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb87"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb87-1"><a href="#cb87-1" aria-hidden="true" tabindex="-1"></a>barrio_sol<span class="ot">&lt;-</span><span class="fu">subset</span>(airbnb_entire,Barrio<span class="sc">==</span><span class="st">"Sol"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><strong>Objetivo : Calcular un modelo lineal que combine alguna de estas variables: * NumBanyos * NumDormitorios * MaxOcupantes * MetrosCuadrados</strong></p>
<p>Primero calculamos la correlación para ver como se relacionan estas variables entre sí.<img src=".png" class="img-fluid"></p>
<p>Vamos a realizar la correlación entre todas las variables numéricas del dataset.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb88"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb88-1"><a href="#cb88-1" aria-hidden="true" tabindex="-1"></a>variable_numericas <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"MaxOcupantes"</span>,<span class="st">"NumBanyos"</span>,<span class="st">"NumDormitorios"</span>,<span class="st">"NumCamas"</span>,<span class="st">"Puntuacion"</span>,<span class="st">"MetrosCuadrados"</span>,<span class="st">"Precio"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb89"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb89-1"><a href="#cb89-1" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(<span class="fu">cor</span>(barrio_sol[variable_numericas],<span class="at">use=</span><span class="st">"complete.obs"</span>),<span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                MaxOcupantes NumBanyos NumDormitorios NumCamas Puntuacion
MaxOcupantes            1.00      0.70           0.79     0.93      -0.18
NumBanyos               0.70      1.00           0.69     0.61      -0.20
NumDormitorios          0.79      0.69           1.00     0.76      -0.05
NumCamas                0.93      0.61           0.76     1.00      -0.22
Puntuacion             -0.18     -0.20          -0.05    -0.22       1.00
MetrosCuadrados         0.43      0.48           0.57     0.35       0.01
Precio                  0.53      0.60           0.72     0.45       0.12
                MetrosCuadrados Precio
MaxOcupantes               0.43   0.53
NumBanyos                  0.48   0.60
NumDormitorios             0.57   0.72
NumCamas                   0.35   0.45
Puntuacion                 0.01   0.12
MetrosCuadrados            1.00   0.64
Precio                     0.64   1.00</code></pre>
</div>
</div>
<p>Observamos que la puntuación no tiene buena correlación con las demas por lo cual la eliminamos para los siguientes pasos.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb91"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb91-1"><a href="#cb91-1" aria-hidden="true" tabindex="-1"></a>variable_numericas <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"MaxOcupantes"</span>,<span class="st">"NumBanyos"</span>,<span class="st">"NumDormitorios"</span>,<span class="st">"NumCamas"</span>,<span class="st">"MetrosCuadrados"</span>,<span class="st">"Precio"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><strong>Se observa que la correlación entre el número de dormitorios y los metros cuadrados es sorprendentemente baja. ¿Son de fiar esos números?</strong></p>
<p>Entre el número de dormitorios y los metros cuadrados se observa una correlación no muy alta 0.57 y usualmente debería ser mas correlacionada debido a que son variables que tienen mucha relación ( a mayor número de dormitorios mayor serán los metros cuadrados de este).</p>
<p><strong>Mediante un histograma o curvas de densidad podemos descartar números que no tienen sentido en el dataframe barrio_sol, para tener una matriz de correlación que tenga mayor sentido.</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb92"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb92-1"><a href="#cb92-1" aria-hidden="true" tabindex="-1"></a>datos <span class="ot">&lt;-</span> <span class="fu">na.omit</span>(barrio_sol<span class="sc">$</span>MetrosCuadrados)</span>
<span id="cb92-2"><a href="#cb92-2" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(datos, <span class="at">breaks =</span> <span class="fu">seq</span>(<span class="fu">min</span>(datos), <span class="fu">max</span>(datos) <span class="sc">+</span> <span class="dv">10</span>, <span class="at">by =</span> <span class="dv">10</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Bartolome_Flores_Vciaria-PracticaFinal_files/figure-html/unnamed-chunk-39-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Mediante el histograma observamos que hay muchos datos que no son coherentes ( pisos con 0 metros cuadrados) . Por lo cual eliminaremos aquello con aquellos pisos de barrio del Sol que tienen al menos 30 metros cuadrados y que tendan valores omitidos.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb93"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb93-1"><a href="#cb93-1" aria-hidden="true" tabindex="-1"></a>barrio_sol_modelo <span class="ot">&lt;-</span> <span class="fu">subset</span>(barrio_sol,MetrosCuadrados <span class="sc">&gt;=</span> <span class="dv">30</span>)</span>
<span id="cb93-2"><a href="#cb93-2" aria-hidden="true" tabindex="-1"></a>barrio_sol_modelo <span class="ot">&lt;-</span> <span class="fu">na.omit</span>(barrio_sol_modelo)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Volvemo a realizar la correlación de los datos con la limpieza de datos en la columna “MetrosCuadrados”</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb94"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb94-1"><a href="#cb94-1" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(<span class="fu">cor</span>(barrio_sol[variable_numericas],<span class="at">use=</span><span class="st">"complete.obs"</span>),<span class="at">digits=</span><span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                MaxOcupantes NumBanyos NumDormitorios NumCamas MetrosCuadrados
MaxOcupantes            1.00      0.70           0.79     0.93            0.43
NumBanyos               0.70      1.00           0.69     0.61            0.48
NumDormitorios          0.79      0.69           1.00     0.76            0.57
NumCamas                0.93      0.61           0.76     1.00            0.35
MetrosCuadrados         0.43      0.48           0.57     0.35            1.00
Precio                  0.53      0.60           0.72     0.45            0.64
                Precio
MaxOcupantes      0.53
NumBanyos         0.60
NumDormitorios    0.72
NumCamas          0.45
MetrosCuadrados   0.64
Precio            1.00</code></pre>
</div>
</div>
<p>Como se puede comprobar en la nueva matriz de correlaciones la relación entre metros cuadrados y y número de dormitorios ha subido de 0.57 a 0.83 debido a la limpieza de datos hecha.</p>
<p><strong>Una vez que hayamos filtrado los datos correspondientes calcular el valor o la combinación de valores que mejor nos permite obtener el precio de un inmueble.</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb96"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb96-1"><a href="#cb96-1" aria-hidden="true" tabindex="-1"></a>model1<span class="ot">&lt;-</span><span class="fu">lm</span>(<span class="at">data=</span>barrio_sol_modelo,<span class="at">formula =</span> Precio<span class="sc">~</span>NumBanyos<span class="sc">+</span>NumCamas<span class="sc">+</span>NumDormitorios<span class="sc">+</span>MaxOcupantes<span class="sc">+</span>MetrosCuadrados)</span>
<span id="cb96-2"><a href="#cb96-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Precio ~ NumBanyos + NumCamas + NumDormitorios + 
    MaxOcupantes + MetrosCuadrados, data = barrio_sol_modelo)

Residuals:
    Min      1Q  Median      3Q     Max 
-70.011 -16.053  -0.836  19.627  66.509 

Coefficients:
                Estimate Std. Error t value Pr(&gt;|t|)   
(Intercept)      16.9123    15.1344   1.117  0.27442   
NumBanyos         8.5530    14.4976   0.590  0.56051   
NumCamas         -7.8542     5.6971  -1.379  0.18022   
NumDormitorios   31.4809     9.1192   3.452  0.00199 **
MaxOcupantes      8.2045     6.0911   1.347  0.19008   
MetrosCuadrados   0.1523     0.2087   0.730  0.47210   
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 29.39 on 25 degrees of freedom
Multiple R-squared:  0.8113,    Adjusted R-squared:  0.7735 
F-statistic:  21.5 on 5 and 25 DF,  p-value: 2.547e-08</code></pre>
</div>
</div>
<p>Observamos que la variabla que nos aporta mayor p-valor es NumDormitorios y que por cada dormitorio mas el precio aumenta 31 € , seguida de número de baños , MaxOcupantes y MetrosCuadrados. Por último tenemos la variable Numcamas que nos resta valor al precio por cada una que tiene.</p>
<p>Calculamos ahora otra vez el modelo lineal quitando las variables menos significaticas que en este caso sería NumCamas y MetrosCuadrados</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb98"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb98-1"><a href="#cb98-1" aria-hidden="true" tabindex="-1"></a>model2<span class="ot">&lt;-</span><span class="fu">lm</span>(<span class="at">data=</span>barrio_sol_modelo,<span class="at">formula =</span> Precio<span class="sc">~</span>NumBanyos<span class="sc">+</span>NumDormitorios<span class="sc">+</span>MaxOcupantes)</span>
<span id="cb98-2"><a href="#cb98-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Precio ~ NumBanyos + NumDormitorios + MaxOcupantes, 
    data = barrio_sol_modelo)

Residuals:
    Min      1Q  Median      3Q     Max 
-80.196 -14.727  -0.301  18.288  62.586 

Coefficients:
               Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)      29.004     12.905   2.248    0.033 *  
NumBanyos        10.228     14.528   0.704    0.487    
NumDormitorios   32.112      6.557   4.897 4.02e-05 ***
MaxOcupantes      2.739      4.450   0.616    0.543    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 29.73 on 27 degrees of freedom
Multiple R-squared:  0.7915,    Adjusted R-squared:  0.7683 
F-statistic: 34.16 on 3 and 27 DF,  p-value: 2.46e-09</code></pre>
</div>
</div>
<p>Con este nuevo modelo lineal con soló 3 variables tiene un R-squared un poco peor pero es lo normal debido a cómo funciona R y el Residual standard error ha bajado un poco.</p>
<p><strong>¿Que variable es más fiable para conocer el precio de un inmueble, el número de habitaciones o los metros cuadrados?</strong></p>
<p>Es más fiable la variable número de habitaciones respecto al de metros cuadrados debido a que en el primer modelo realizado el número de habitaciones incrementa el precio 31.48 € por cada una mientras que los metros cuadrados aumenta por cada uno 0.1523 € por cada uno. Esto también es debido que por cada unidad de número de habitaciones tiene mayor relevacia en el modelo que por cada unidad de metros cuadrados.</p>
<p>Además el p-valor de número de habitaciones es de 0.00199 que es bastante significativo respecto al de metros cuadrados que es de 0.47210 que no aporta tanto valor.</p>
<p><strong>Responde con su correspondiente margen de error del 95%, ¿cuantos euros incrementa el precio del alquiler por cada metro cuadrado extra del piso?</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb100"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb100-1"><a href="#cb100-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Creamos el modelo lineal para el precio dependiendo de los metros cuadrados</span></span>
<span id="cb100-2"><a href="#cb100-2" aria-hidden="true" tabindex="-1"></a>modelMetrosCuadrados<span class="ot">&lt;-</span><span class="fu">lm</span>(<span class="at">data=</span>barrio_sol_modelo,<span class="at">formula =</span> Precio <span class="sc">~</span> MetrosCuadrados)</span>
<span id="cb100-3"><a href="#cb100-3" aria-hidden="true" tabindex="-1"></a><span class="co">#Obtenemos el intervalo de confianza para el modelo anterior para el margen de error del 95%</span></span>
<span id="cb100-4"><a href="#cb100-4" aria-hidden="true" tabindex="-1"></a>confintMetrosCuadrados <span class="ot">&lt;-</span> <span class="fu">confint</span>(modelMetrosCuadrados,<span class="at">level =</span> <span class="fl">0.95</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb101"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb101-1"><a href="#cb101-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"El precio del alquiler aumenta"</span>,modelMetrosCuadrados<span class="sc">$</span>coefficients[<span class="st">"MetrosCuadrados"</span>],<span class="st">"por cada metro cuadrado extras del piso siguiendo un margen de erro del 95% el margen es: </span><span class="sc">\n</span><span class="st">"</span>,</span>
<span id="cb101-2"><a href="#cb101-2" aria-hidden="true" tabindex="-1"></a><span class="st">"["</span>,confintMetrosCuadrados[<span class="st">"MetrosCuadrados"</span>,<span class="st">"2.5 %"</span>],<span class="st">","</span>,</span>
<span id="cb101-3"><a href="#cb101-3" aria-hidden="true" tabindex="-1"></a>confintMetrosCuadrados[<span class="st">"MetrosCuadrados"</span>,<span class="st">"97.5 %"</span>],<span class="st">"]"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>El precio del alquiler aumenta 1.030491 por cada metro cuadrado extras del piso siguiendo un margen de erro del 95% el margen es: 
 [ 0.7069076 , 1.354075 ]</code></pre>
</div>
</div>
<p><strong>Responde con su correspondiente margen de error del 95%, ¿cuantos euros incrementa el precio del alquiler por cada habitación?</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb103"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb103-1"><a href="#cb103-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Creamos el modelo lineal para el precio dependiendo del numero de domitorios</span></span>
<span id="cb103-2"><a href="#cb103-2" aria-hidden="true" tabindex="-1"></a>modelNumDormitorios<span class="ot">&lt;-</span><span class="fu">lm</span>(<span class="at">data=</span>barrio_sol_modelo,<span class="at">formula =</span> Precio <span class="sc">~</span> NumDormitorios)</span>
<span id="cb103-3"><a href="#cb103-3" aria-hidden="true" tabindex="-1"></a><span class="co">#Obtenemos el intervalo de confianza para el modelo anterior para el margen de error del 95%</span></span>
<span id="cb103-4"><a href="#cb103-4" aria-hidden="true" tabindex="-1"></a>confintNumDormitorios <span class="ot">&lt;-</span> <span class="fu">confint</span>(modelNumDormitorios,<span class="at">level =</span> <span class="fl">0.95</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb104"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb104-1"><a href="#cb104-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"El precio del alquiler aumenta"</span>,modelNumDormitorios<span class="sc">$</span>coefficients[<span class="st">"NumDormitorios"</span>],<span class="st">"por cada metro cuadrado extras del piso siguiendo un margen de erro del 95% el margen es: </span><span class="sc">\n</span><span class="st">"</span>,</span>
<span id="cb104-2"><a href="#cb104-2" aria-hidden="true" tabindex="-1"></a><span class="st">"["</span>,confintNumDormitorios[<span class="st">"NumDormitorios"</span>,<span class="st">"2.5 %"</span>],<span class="st">","</span>,</span>
<span id="cb104-3"><a href="#cb104-3" aria-hidden="true" tabindex="-1"></a>confintNumDormitorios[<span class="st">"NumDormitorios"</span>,<span class="st">"97.5 %"</span>],<span class="st">"]"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>El precio del alquiler aumenta 40.15548 por cada metro cuadrado extras del piso siguiendo un margen de erro del 95% el margen es: 
 [ 31.86153 , 48.44942 ]</code></pre>
</div>
</div>
<p><strong>¿Cual es la probabilidad de encontrar, en el barrio de Sol, un apartamento en alquiler con 3 dormitorios? ¿Cual es el intervalo de confianza de esa probabilidad?</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb106"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb106-1"><a href="#cb106-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Numero de apartamentos en el Barrio de sol</span></span>
<span id="cb106-2"><a href="#cb106-2" aria-hidden="true" tabindex="-1"></a>barrio_sol_apart <span class="ot">&lt;-</span> <span class="fu">nrow</span>(barrio_sol)</span>
<span id="cb106-3"><a href="#cb106-3" aria-hidden="true" tabindex="-1"></a><span class="co">#Numero de apartamentos en el Barrio de sol con 3 dormtorios</span></span>
<span id="cb106-4"><a href="#cb106-4" aria-hidden="true" tabindex="-1"></a>barrio_sol_3_dormitorios_apart <span class="ot">&lt;-</span> <span class="fu">nrow</span>(<span class="fu">subset</span>(barrio_sol,NumDormitorios <span class="sc">==</span> <span class="dv">3</span>))</span>
<span id="cb106-5"><a href="#cb106-5" aria-hidden="true" tabindex="-1"></a><span class="co">#Aplicamos la binomial con un nivel de confianza del 95%</span></span>
<span id="cb106-6"><a href="#cb106-6" aria-hidden="true" tabindex="-1"></a>binomtest <span class="ot">&lt;-</span> <span class="fu">binom.test</span>(barrio_sol_3_dormitorios_apart,barrio_sol_apart,<span class="at">conf.level=</span><span class="fl">0.95</span>)</span>
<span id="cb106-7"><a href="#cb106-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb106-8"><a href="#cb106-8" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"La probabilidad de encontrar, en el barrio de Sol,</span><span class="sc">\n</span><span class="st">un apartamento en alquiler con 3 habitaciones es</span><span class="sc">\n</span><span class="st">"</span>,<span class="fu">round</span>(binomtest<span class="sc">$</span>estimate,<span class="dv">4</span>),<span class="st">"con un intervalo de confianza al "</span>,<span class="fu">attr</span>(binomtest<span class="sc">$</span>conf.int, <span class="st">"conf.level"</span>),<span class="st">" es:</span><span class="sc">\n</span><span class="st">"</span>,<span class="st">"["</span>,<span class="fu">round</span>(binomtest<span class="sc">$</span>conf.int[<span class="dv">1</span>],<span class="dv">4</span>),<span class="st">","</span>,<span class="fu">round</span>(binomtest<span class="sc">$</span>conf.int[<span class="dv">2</span>],<span class="dv">4</span>),<span class="st">"]"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>La probabilidad de encontrar, en el barrio de Sol,
un apartamento en alquiler con 3 habitaciones es
 0.0785 con un intervalo de confianza al  0.95  es:
 [ 0.0597 , 0.1009 ]</code></pre>
</div>
</div>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>